import {
  AppleIcon,
  ArrowRightIcon,
  AwardIcon,
  BellIcon,
  BikeIcon,
  BookIcon,
  BookOpenIcon,
  BrainIcon,
  BusIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CatIcon,
  CheckIcon,
  CircleHelpIcon,
  ClockIcon,
  CloudRainIcon,
  CloudSunIcon,
  DogIcon,
  FishIcon,
  FlagIcon,
  GamepadIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadphonesIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  LightbulbIcon,
  MapPinIcon,
  MessageCircleIcon,
  MicIcon,
  MoonIcon,
  MusicIcon,
  PaletteIcon,
  PencilIcon,
  PlaneIcon,
  RabbitIcon,
  RulerIcon,
  SchoolIcon,
  ShirtIcon,
  SmileIcon,
  SnowflakeIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  ThumbsUpIcon,
  TreePineIcon,
  TrophyIcon,
  UserIcon,
  UsersIcon,
  UtensilsIcon,
  VolumeIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react"

/**
 * The icon library of the Icon tool. Designs store the name; a name that is
 * not listed here renders as a question mark (so older designs never break).
 */
export const DESIGN_ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  star: { icon: StarIcon, label: "Star" },
  heart: { icon: HeartIcon, label: "Heart" },
  smile: { icon: SmileIcon, label: "Smile" },
  "thumbs-up": { icon: ThumbsUpIcon, label: "Thumbs up" },
  check: { icon: CheckIcon, label: "Tick" },
  x: { icon: XIcon, label: "Cross" },
  "circle-help": { icon: CircleHelpIcon, label: "Question" },
  lightbulb: { icon: LightbulbIcon, label: "Idea" },
  sparkles: { icon: SparklesIcon, label: "Sparkles" },
  award: { icon: AwardIcon, label: "Award" },
  trophy: { icon: TrophyIcon, label: "Trophy" },
  flag: { icon: FlagIcon, label: "Flag" },
  "arrow-right": { icon: ArrowRightIcon, label: "Arrow" },
  "book-open": { icon: BookOpenIcon, label: "Open book" },
  book: { icon: BookIcon, label: "Book" },
  pencil: { icon: PencilIcon, label: "Pencil" },
  ruler: { icon: RulerIcon, label: "Ruler" },
  calculator: { icon: CalculatorIcon, label: "Calculator" },
  "graduation-cap": { icon: GraduationCapIcon, label: "Graduation" },
  school: { icon: SchoolIcon, label: "School" },
  brain: { icon: BrainIcon, label: "Think" },
  "message-circle": { icon: MessageCircleIcon, label: "Speak" },
  mic: { icon: MicIcon, label: "Microphone" },
  headphones: { icon: HeadphonesIcon, label: "Listen" },
  volume: { icon: VolumeIcon, label: "Sound" },
  music: { icon: MusicIcon, label: "Music" },
  image: { icon: ImageIcon, label: "Picture" },
  camera: { icon: CameraIcon, label: "Camera" },
  palette: { icon: PaletteIcon, label: "Art" },
  gamepad: { icon: GamepadIcon, label: "Game" },
  clock: { icon: ClockIcon, label: "Time" },
  calendar: { icon: CalendarIcon, label: "Calendar" },
  bell: { icon: BellIcon, label: "Bell" },
  user: { icon: UserIcon, label: "Person" },
  users: { icon: UsersIcon, label: "People" },
  home: { icon: HomeIcon, label: "Home" },
  "map-pin": { icon: MapPinIcon, label: "Place" },
  globe: { icon: GlobeIcon, label: "World" },
  sun: { icon: SunIcon, label: "Sun" },
  "cloud-sun": { icon: CloudSunIcon, label: "Weather" },
  "cloud-rain": { icon: CloudRainIcon, label: "Rain" },
  snowflake: { icon: SnowflakeIcon, label: "Snow" },
  moon: { icon: MoonIcon, label: "Moon" },
  "tree-pine": { icon: TreePineIcon, label: "Tree" },
  cat: { icon: CatIcon, label: "Cat" },
  dog: { icon: DogIcon, label: "Dog" },
  fish: { icon: FishIcon, label: "Fish" },
  rabbit: { icon: RabbitIcon, label: "Rabbit" },
  apple: { icon: AppleIcon, label: "Apple" },
  cake: { icon: CakeIcon, label: "Cake" },
  utensils: { icon: UtensilsIcon, label: "Food" },
  shirt: { icon: ShirtIcon, label: "Clothes" },
  car: { icon: CarIcon, label: "Car" },
  bus: { icon: BusIcon, label: "Bus" },
  bike: { icon: BikeIcon, label: "Bike" },
  plane: { icon: PlaneIcon, label: "Plane" },
}

export function designIcon(name: string) {
  return DESIGN_ICONS[name]?.icon ?? CircleHelpIcon
}
